version: 2
jobs:
  build:
    working_directory: /retyped
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: 'Install OPAM'
          command: 'sudo apt-get install opam'
      - run:
          name: 'Setup OPAM'
          command: 'opam init -y && opam update && opam switch 4.02.3  && eval $(opam config env)'
      - run:
          name: 'Install OCaml dependencies'
          command: 'opam install -y ocamlfind js_of_ocaml sedlex reason'
      - run:
          name: 'Clean build artifacts'
          command: 'make clean'
      - run:
          name: 'Build JS files'
          command: 'make'
      - run:
          name: 'Install JS dependencies'
          command: 'npm install'
      - run:
          name: 'Run tests'
          command: 'npm test'
